### ISSUE TITLE
Always 32 bits set

### ISSUE THREAD

**Issue by thomasd3** [coenm/ImageHash#17]
When using the perceptual hash, there are always 32 bits set in the output.

Is that normal?

**Comment by coenm** [comment]
I've looked at the code and my implementation of perceptual hash uses the median to calculate the threshold value and that is why the output has always 32 bits set (ie, 32 bits pixels are less then the median, and the other 32 bits are bigger).

So, Is this wrong? 
I don't know. I can imagine that instead of the median, the average should be used (like average hash) and leeds to beter results comparing images. 

What do you think?

**Comment by thomasd3** [comment]
The average is not going to be practical when you have a growing collection of images because it would need to be recalculated; I didn't really think of the implication of the 32 bits set, it's just something I noticed in our collection and I was wondering if it was normal :)
