### ISSUE TITLE
Zip download is missing files and won't build

### ISSUE THREAD

**Issue by daviddennisei** [coenm/ImageHash#30]
I downloaded ImageHash-develop.zip from GitHub and opened the ImageHash.sln in VS 2019. It would not build, complaining about missing files from the .git folder (which did not exist). I then downloaded it with GitHub Desktop. This version built OK. 

 I was able to get the ImageHash solution from the zip file to build by copying the .git folder from the GitHub Desktop version to it. 

Expected result: You should be able to build and run ImageHash from the GitHub zip download.

**Comment by coenm** [comment]
You are right. It should be possible to compile  ImageHash from a Github zip download, but it isn't.

Glad to hear that you found a workaround by cloning the repository (which includes the .git folder).

I use GitVersion to determine the version, and to stamp the output dll and package with that version. GitVersion uses git (i.e. the .git folder) to calculate the version. That's the reason it is not working as expected.

At this moment, I'm not going to fix this because to support GitHub zip downloads, I should replace GitVersion with something else, try to make Github include the .git folder or maybe something else. I don't have the time for that right now.

If you have a fix, you can create a Pull Request.

**Comment by daviddennisei** [comment]
I have a workaround, and am not conversant enough with ImageHash or git (I used mercurial for my repos) to attempt a fix. My opinion is that ImageHash should have its own standalone version scheme, independent of github.

-          Thanks

 

Best regards,

 

David Ei

   Email:     <mailto:david.ei@eieioh.net> david.ei@eieioh.net

   Home:  (734) 449-2404

   Cell:       (734) 353-9542
